export const PROFICIENCY_TOPIC_META_DATA = [{
  domainCode: 'CC',
  domainName: null,
  domainSeq: 1,
  topics: [{
    topicCode: 'CSE.1',
    topicDesc: null,
    topicName: null,
    topicSeq: 1,
    domainCode: 'CC',
    domainSeq: 1
  }, {
    topicCode: 'NOB.2',
    topicDesc: null,
    topicName: null,
    topicSeq: 2,
    domainCode: 'CC',
    domainSeq: 1
  }, {
    topicCode: 'CNU.3',
    topicDesc: null,
    topicName: null,
    topicSeq: 3,
    domainCode: 'CC',
    domainSeq: 1
  }]
}, {
  domainCode: 'OAT',
  domainName: null,
  domainSeq: 2,
  topics: [{
    topicCode: 'UAS.1',
    topicDesc: null,
    topicName: null,
    topicSeq: 1,
    domainCode: 'OAT',
    domainSeq: 2
  }, {
    topicCode: 'ASS.2',
    topicDesc: null,
    topicName: null,
    topicSeq: 2,
    domainCode: 'OAT',
    domainSeq: 2
  }, {
    topicCode: 'RAS.3',
    topicDesc: null,
    topicName: null,
    topicSeq: 3,
    domainCode: 'OAT',
    domainSeq: 2
  }, {
    topicCode: 'AS2.4',
    topicDesc: null,
    topicName: null,
    topicSeq: 4,
    domainCode: 'OAT',
    domainSeq: 2
  }, {
    topicCode: 'ASE.5',
    topicDesc: null,
    topicName: null,
    topicSeq: 5,
    domainCode: 'OAT',
    domainSeq: 2
  }, {
    topicCode: 'RSP.6',
    topicDesc: null,
    topicName: null,
    topicSeq: 6,
    domainCode: 'OAT',
    domainSeq: 2
  }, {
    topicCode: 'AS2.7',
    topicDesc: null,
    topicName: null,
    topicSeq: 7,
    domainCode: 'OAT',
    domainSeq: 2
  }, {
    topicCode: 'WEG.8',
    topicDesc: null,
    topicName: null,
    topicSeq: 8,
    domainCode: 'OAT',
    domainSeq: 2
  }, {
    topicCode: 'RSP.9',
    topicDesc: null,
    topicName: null,
    topicSeq: 9,
    domainCode: 'OAT',
    domainSeq: 2
  }, {
    topicCode: 'UPM.10',
    topicDesc: null,
    topicName: null,
    topicSeq: 10,
    domainCode: 'OAT',
    domainSeq: 2
  }, {
    topicCode: 'MD1.11',
    topicDesc: null,
    topicName: null,
    topicSeq: 11,
    domainCode: 'OAT',
    domainSeq: 2
  }, {
    topicCode: 'SPI.12',
    topicDesc: null,
    topicName: null,
    topicSeq: 12,
    domainCode: 'OAT',
    domainSeq: 2
  }, {
    topicCode: 'UFO.13',
    topicDesc: null,
    topicName: null,
    topicSeq: 13,
    domainCode: 'OAT',
    domainSeq: 2
  }, {
    topicCode: 'GFF.14',
    topicDesc: null,
    topicName: null,
    topicSeq: 14,
    domainCode: 'OAT',
    domainSeq: 2
  }, {
    topicCode: 'GAP.15',
    topicDesc: null,
    topicName: null,
    topicSeq: 15,
    domainCode: 'OAT',
    domainSeq: 2
  }, {
    topicCode: 'WIN.16',
    topicDesc: null,
    topicName: null,
    topicSeq: 16,
    domainCode: 'OAT',
    domainSeq: 2
  }, {
    topicCode: 'APR.17',
    topicDesc: null,
    topicName: null,
    topicSeq: 17,
    domainCode: 'OAT',
    domainSeq: 2
  }]
}, {
  domainCode: 'NOBT',
  domainName: null,
  domainSeq: 3,
  topics: [{
    topicCode: 'FPV.1',
    topicDesc: null,
    topicName: null,
    topicSeq: 1,
    domainCode: 'NOBT',
    domainSeq: 3
  }, {
    topicCode: 'ECS.2',
    topicDesc: null,
    topicName: null,
    topicSeq: 2,
    domainCode: 'NOBT',
    domainSeq: 3
  }, {
    topicCode: 'UPV.3',
    topicDesc: null,
    topicName: null,
    topicSeq: 3,
    domainCode: 'NOBT',
    domainSeq: 3
  }, {
    topicCode: 'UPV.4',
    topicDesc: null,
    topicName: null,
    topicSeq: 4,
    domainCode: 'NOBT',
    domainSeq: 3
  }, {
    topicCode: 'UPV.5',
    topicDesc: null,
    topicName: null,
    topicSeq: 5,
    domainCode: 'NOBT',
    domainSeq: 3
  }, {
    topicCode: 'UPV.6',
    topicDesc: null,
    topicName: null,
    topicSeq: 6,
    domainCode: 'NOBT',
    domainSeq: 3
  }, {
    topicCode: 'UPV.7',
    topicDesc: null,
    topicName: null,
    topicSeq: 7,
    domainCode: 'NOBT',
    domainSeq: 3
  }, {
    topicCode: 'POMA.8',
    topicDesc: null,
    topicName: null,
    topicSeq: 8,
    domainCode: 'NOBT',
    domainSeq: 3
  }, {
    topicCode: 'GPV.9',
    topicDesc: null,
    topicName: null,
    topicSeq: 9,
    domainCode: 'NOBT',
    domainSeq: 3
  }, {
    topicCode: 'UPV.10',
    topicDesc: null,
    topicName: null,
    topicSeq: 10,
    domainCode: 'NOBT',
    domainSeq: 3
  }, {
    topicCode: 'RWC.11',
    topicDesc: null,
    topicName: null,
    topicSeq: 11,
    domainCode: 'NOBT',
    domainSeq: 3
  }, {
    topicCode: 'RDA.12',
    topicDesc: null,
    topicName: null,
    topicSeq: 12,
    domainCode: 'NOBT',
    domainSeq: 3
  }, {
    topicCode: 'POM.13',
    topicDesc: null,
    topicName: null,
    topicSeq: 13,
    domainCode: 'NOBT',
    domainSeq: 3
  }]
}, {
  domainCode: 'NOF',
  domainName: null,
  domainSeq: 4,
  topics: [{
    topicCode: 'DAU.1',
    topicDesc: null,
    topicName: null,
    topicSeq: 1,
    domainCode: 'NOF',
    domainSeq: 4
  }, {
    topicCode: 'EEF.2',
    topicDesc: null,
    topicName: null,
    topicSeq: 2,
    domainCode: 'NOF',
    domainSeq: 4
  }, {
    topicCode: 'EUF.3',
    topicDesc: null,
    topicName: null,
    topicSeq: 3,
    domainCode: 'NOF',
    domainSeq: 4
  }, {
    topicCode: 'UFT.4',
    topicDesc: null,
    topicName: null,
    topicSeq: 4,
    domainCode: 'NOF',
    domainSeq: 4
  }, {
    topicCode: 'UFT.5',
    topicDesc: null,
    topicName: null,
    topicSeq: 5,
    domainCode: 'NOF',
    domainSeq: 4
  }, {
    topicCode: 'UDN.6',
    topicDesc: null,
    topicName: null,
    topicSeq: 6,
    domainCode: 'NOF',
    domainSeq: 4
  }, {
    topicCode: 'UEF.7',
    topicDesc: null,
    topicName: null,
    topicSeq: 7,
    domainCode: 'NOF',
    domainSeq: 4
  }, {
    topicCode: 'IFT.8',
    topicDesc: null,
    topicName: null,
    topicSeq: 8,
    domainCode: 'NOF',
    domainSeq: 4
  }, {
    topicCode: 'AEP.9',
    topicDesc: null,
    topicName: null,
    topicSeq: 9,
    domainCode: 'NOF',
    domainSeq: 4
  }, {
    topicCode: 'IMA.10',
    topicDesc: null,
    topicName: null,
    topicSeq: 10,
    domainCode: 'NOF',
    domainSeq: 4
  }, {
    topicCode: 'MFM.11',
    topicDesc: null,
    topicName: null,
    topicSeq: 11,
    domainCode: 'NOF',
    domainSeq: 4
  }, {
    topicCode: 'DFR.12',
    topicDesc: null,
    topicName: null,
    topicSeq: 12,
    domainCode: 'NOF',
    domainSeq: 4
  }]
}, {
  domainCode: 'MD',
  domainName: null,
  domainSeq: 5,
  topics: [{
    topicCode: 'MAT.1',
    topicDesc: null,
    topicName: null,
    topicSeq: 1,
    domainCode: 'MD',
    domainSeq: 5
  }, {
    topicCode: 'CCO.2',
    topicDesc: null,
    topicName: null,
    topicSeq: 2,
    domainCode: 'MD',
    domainSeq: 5
  }, {
    topicCode: 'MLE.3',
    topicDesc: null,
    topicName: null,
    topicSeq: 3,
    domainCode: 'MD',
    domainSeq: 5
  }, {
    topicCode: 'TWT.4',
    topicDesc: null,
    topicName: null,
    topicSeq: 4,
    domainCode: 'MD',
    domainSeq: 5
  }, {
    topicCode: 'RID.5',
    topicDesc: null,
    topicName: null,
    topicSeq: 5,
    domainCode: 'MD',
    domainSeq: 5
  }, {
    topicCode: 'MEL.6',
    topicDesc: null,
    topicName: null,
    topicSeq: 6,
    domainCode: 'MD',
    domainSeq: 5
  }, {
    topicCode: 'RAS.7',
    topicDesc: null,
    topicName: null,
    topicSeq: 7,
    domainCode: 'MD',
    domainSeq: 5
  }, {
    topicCode: 'WTM.8',
    topicDesc: null,
    topicName: null,
    topicSeq: 8,
    domainCode: 'MD',
    domainSeq: 5
  }, {
    topicCode: 'RID.9',
    topicDesc: null,
    topicName: null,
    topicSeq: 9,
    domainCode: 'MD',
    domainSeq: 5
  }, {
    topicCode: 'SPI.10',
    topicDesc: null,
    topicName: null,
    topicSeq: 10,
    domainCode: 'MD',
    domainSeq: 5
  }, {
    topicCode: 'IRD.11',
    topicDesc: null,
    topicName: null,
    topicSeq: 11,
    domainCode: 'MD',
    domainSeq: 5
  }, {
    topicCode: 'UCA.12',
    topicDesc: null,
    topicName: null,
    topicSeq: 12,
    domainCode: 'MD',
    domainSeq: 5
  }, {
    topicCode: 'RAO.13',
    topicDesc: null,
    topicName: null,
    topicSeq: 13,
    domainCode: 'MD',
    domainSeq: 5
  }, {
    topicCode: 'GMR.14',
    topicDesc: null,
    topicName: null,
    topicSeq: 14,
    domainCode: 'MD',
    domainSeq: 5
  }, {
    topicCode: 'SPI.15',
    topicDesc: null,
    topicName: null,
    topicSeq: 15,
    domainCode: 'MD',
    domainSeq: 5
  }, {
    topicCode: 'RIDD.16',
    topicDesc: null,
    topicName: null,
    topicSeq: 16,
    domainCode: 'MD',
    domainSeq: 5
  }, {
    topicCode: 'GMU.17',
    topicDesc: null,
    topicName: null,
    topicSeq: 17,
    domainCode: 'MD',
    domainSeq: 5
  }, {
    topicCode: 'CLM.18',
    topicDesc: null,
    topicName: null,
    topicSeq: 18,
    domainCode: 'MD',
    domainSeq: 5
  }, {
    topicCode: 'RIDM.19',
    topicDesc: null,
    topicName: null,
    topicSeq: 19,
    domainCode: 'MD',
    domainSeq: 5
  }, {
    topicCode: 'RVA.20',
    topicDesc: null,
    topicName: null,
    topicSeq: 20,
    domainCode: 'MD',
    domainSeq: 5
  }, {
    topicCode: 'RVO.21',
    topicDesc: null,
    topicName: null,
    topicSeq: 21,
    domainCode: 'MD',
    domainSeq: 5
  }]
}, {
  domainCode: 'G',
  domainName: null,
  domainSeq: 6,
  topics: [{
    topicCode: 'IDS.1',
    topicDesc: null,
    topicName: null,
    topicSeq: 1,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'ACS.2',
    topicDesc: null,
    topicName: null,
    topicSeq: 2,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'RST.3',
    topicDesc: null,
    topicName: null,
    topicSeq: 3,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'RST.4',
    topicDesc: null,
    topicName: null,
    topicSeq: 4,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'ASA.5',
    topicDesc: null,
    topicName: null,
    topicSeq: 5,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'DIL.6',
    topicDesc: null,
    topicName: null,
    topicSeq: 6,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'ULS.7',
    topicDesc: null,
    topicName: null,
    topicSeq: 7,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'GPC.8',
    topicDesc: null,
    topicName: null,
    topicSeq: 8,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'CTF.9',
    topicDesc: null,
    topicName: null,
    topicSeq: 9,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'FAT.10',
    topicDesc: null,
    topicName: null,
    topicSeq: 10,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'FVR.11',
    topicDesc: null,
    topicName: null,
    topicSeq: 11,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'DPC.12',
    topicDesc: null,
    topicName: null,
    topicSeq: 12,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'RTF.13',
    topicDesc: null,
    topicName: null,
    topicSeq: 13,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'SPI.14',
    topicDesc: null,
    topicName: null,
    topicSeq: 14,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'DCD.15',
    topicDesc: null,
    topicName: null,
    topicSeq: 15,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'ACC.16',
    topicDesc: null,
    topicName: null,
    topicSeq: 16,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'SPS.17',
    topicDesc: null,
    topicName: null,
    topicSeq: 17,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'SRM.18',
    topicDesc: null,
    topicName: null,
    topicSeq: 18,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'VEP.19',
    topicDesc: null,
    topicName: null,
    topicSeq: 19,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'UCO.20',
    topicDesc: null,
    topicName: null,
    topicSeq: 20,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'DED.21',
    topicDesc: null,
    topicName: null,
    topicSeq: 21,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'USI.22',
    topicDesc: null,
    topicName: null,
    topicSeq: 22,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'EFA.23',
    topicDesc: null,
    topicName: null,
    topicSeq: 23,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'UAP.24',
    topicDesc: null,
    topicName: null,
    topicSeq: 24,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'SRP.25',
    topicDesc: null,
    topicName: null,
    topicSeq: 25,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'UPT.26',
    topicDesc: null,
    topicName: null,
    topicSeq: 26,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'IDR.27',
    topicDesc: null,
    topicName: null,
    topicSeq: 27,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'CIC.28',
    topicDesc: null,
    topicName: null,
    topicSeq: 28,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'CTL.29',
    topicDesc: null,
    topicName: null,
    topicSeq: 29,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'FAL.30',
    topicDesc: null,
    topicName: null,
    topicSeq: 30,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'ETP.31',
    topicDesc: null,
    topicName: null,
    topicSeq: 31,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'UCT.32',
    topicDesc: null,
    topicName: null,
    topicSeq: 32,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'PTA.33',
    topicDesc: null,
    topicName: null,
    topicSeq: 33,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'PTA.34',
    topicDesc: null,
    topicName: null,
    topicSeq: 34,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'PTA.35',
    topicDesc: null,
    topicName: null,
    topicSeq: 35,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'MGC.36',
    topicDesc: null,
    topicName: null,
    topicSeq: 36,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'EVF.37',
    topicDesc: null,
    topicName: null,
    topicSeq: 37,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'VRB.38',
    topicDesc: null,
    topicName: null,
    topicSeq: 38,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'DEC.39',
    topicDesc: null,
    topicName: null,
    topicSeq: 39,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'DEP.40',
    topicDesc: null,
    topicName: null,
    topicSeq: 40,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'UCP.41',
    topicDesc: null,
    topicName: null,
    topicSeq: 41,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'FPL.42',
    topicDesc: null,
    topicName: null,
    topicSeq: 42,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'FPA.43',
    topicDesc: null,
    topicName: null,
    topicSeq: 43,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'AGC.44',
    topicDesc: null,
    topicName: null,
    topicSeq: 44,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'UAP.45',
    topicDesc: null,
    topicName: null,
    topicSeq: 45,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'UST.46',
    topicDesc: null,
    topicName: null,
    topicSeq: 46,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'EAC.47',
    topicDesc: null,
    topicName: null,
    topicSeq: 47,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'PTI.48',
    topicDesc: null,
    topicName: null,
    topicSeq: 48,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'DTR.49',
    topicDesc: null,
    topicName: null,
    topicSeq: 49,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'ATG.50',
    topicDesc: null,
    topicName: null,
    topicSeq: 49,
    domainCode: 'G',
    domainSeq: 6
  }, {
    topicCode: 'DEE.51',
    topicDesc: null,
    topicName: null,
    topicSeq: 51,
    domainCode: 'G',
    domainSeq: 6
  }]
}, {
  domainCode: 'RPS',
  domainName: null,
  domainSeq: 7,
  topics: [{
    topicCode: 'URC.1',
    topicDesc: null,
    topicName: null,
    topicSeq: 1,
    domainCode: 'RPS',
    domainSeq: 7
  }, {
    topicCode: 'CUR.2',
    topicDesc: null,
    topicName: null,
    topicSeq: 2,
    domainCode: 'RPS',
    domainSeq: 7
  }, {
    topicCode: 'RRP.3',
    topicDesc: null,
    topicName: null,
    topicSeq: 3,
    domainCode: 'RPS',
    domainSeq: 7
  }, {
    topicCode: 'UPR.4',
    topicDesc: null,
    topicName: null,
    topicSeq: 4,
    domainCode: 'RPS',
    domainSeq: 7
  }]
}, {
  domainCode: 'TNS',
  domainName: null,
  domainSeq: 8,
  topics: [{
    topicCode: 'AEP.1',
    topicDesc: null,
    topicName: null,
    topicSeq: 1,
    domainCode: 'TNS',
    domainSeq: 8
  }, {
    topicCode: 'CFM.2',
    topicDesc: null,
    topicName: null,
    topicSeq: 2,
    domainCode: 'TNS',
    domainSeq: 8
  }, {
    topicCode: 'AEP.3',
    topicDesc: null,
    topicName: null,
    topicSeq: 3,
    domainCode: 'TNS',
    domainSeq: 8
  }, {
    topicCode: 'URN.4',
    topicDesc: null,
    topicName: null,
    topicSeq: 4,
    domainCode: 'TNS',
    domainSeq: 8
  }, {
    topicCode: 'UOA.5',
    topicDesc: null,
    topicName: null,
    topicSeq: 5,
    domainCode: 'TNS',
    domainSeq: 8
  }, {
    topicCode: 'SRM.6',
    topicDesc: null,
    topicName: null,
    topicSeq: 6,
    domainCode: 'TNS',
    domainSeq: 8
  }, {
    topicCode: 'ASR.7',
    topicDesc: null,
    topicName: null,
    topicSeq: 7,
    domainCode: 'TNS',
    domainSeq: 8
  }, {
    topicCode: 'MDR.8',
    topicDesc: null,
    topicName: null,
    topicSeq: 8,
    domainCode: 'TNS',
    domainSeq: 8
  }, {
    topicCode: 'SRM.9',
    topicDesc: null,
    topicName: null,
    topicSeq: 9,
    domainCode: 'TNS',
    domainSeq: 8
  }, {
    topicCode: 'KTT.10',
    topicDesc: null,
    topicName: null,
    topicSeq: 10,
    domainCode: 'TNS',
    domainSeq: 8
  }]
}, {
  domainCode: 'EE',
  domainName: null,
  domainSeq: 9,
  topics: [{
    topicCode: 'WEN.1',
    topicDesc: null,
    topicName: null,
    topicSeq: 1,
    domainCode: 'EE',
    domainSeq: 9
  }, {
    topicCode: 'WRE.2',
    topicDesc: null,
    topicName: null,
    topicSeq: 2,
    domainCode: 'EE',
    domainSeq: 9
  }, {
    topicCode: 'GIE.3',
    topicDesc: null,
    topicName: null,
    topicSeq: 3,
    domainCode: 'EE',
    domainSeq: 9
  }, {
    topicCode: 'RAS.4',
    topicDesc: null,
    topicName: null,
    topicSeq: 4,
    domainCode: 'EE',
    domainSeq: 9
  }, {
    topicCode: 'RAQ.5',
    topicDesc: null,
    topicName: null,
    topicSeq: 5,
    domainCode: 'EE',
    domainSeq: 9
  }, {
    topicCode: 'UPO.6',
    topicDesc: null,
    topicName: null,
    topicSeq: 6,
    domainCode: 'EE',
    domainSeq: 9
  }, {
    topicCode: 'SRP.7',
    topicDesc: null,
    topicName: null,
    topicSeq: 7,
    domainCode: 'EE',
    domainSeq: 9
  }, {
    topicCode: 'KAP.8',
    topicDesc: null,
    topicName: null,
    topicSeq: 8,
    domainCode: 'EE',
    domainSeq: 9
  }, {
    topicCode: 'POI.9',
    topicDesc: null,
    topicName: null,
    topicSeq: 9,
    domainCode: 'EE',
    domainSeq: 9
  }, {
    topicCode: 'UCB.10',
    topicDesc: null,
    topicName: null,
    topicSeq: 10,
    domainCode: 'EE',
    domainSeq: 9
  }, {
    topicCode: 'SLE.11',
    topicDesc: null,
    topicName: null,
    topicSeq: 11,
    domainCode: 'EE',
    domainSeq: 9
  }, {
    topicCode: 'ASP.12',
    topicDesc: null,
    topicName: null,
    topicSeq: 12,
    domainCode: 'EE',
    domainSeq: 9
  }]
}, {
  domainCode: 'NQ',
  domainName: null,
  domainSeq: 10,
  topics: [{
    topicCode: 'EPE.1',
    topicDesc: null,
    topicName: null,
    topicSeq: 1,
    domainCode: 'NQ',
    domainSeq: 10
  }, {
    topicCode: 'UPR.2',
    topicDesc: null,
    topicName: null,
    topicSeq: 2,
    domainCode: 'NQ',
    domainSeq: 10
  }, {
    topicCode: 'RQU.3',
    topicDesc: null,
    topicName: null,
    topicSeq: 3,
    domainCode: 'NQ',
    domainSeq: 10
  }, {
    topicCode: 'PAO.4',
    topicDesc: null,
    topicName: null,
    topicSeq: 4,
    domainCode: 'NQ',
    domainSeq: 10
  }, {
    topicCode: 'UCN.5',
    topicDesc: null,
    topicName: null,
    topicSeq: 5,
    domainCode: 'NQ',
    domainSeq: 10
  }, {
    topicCode: 'AFT.6',
    topicDesc: null,
    topicName: null,
    topicSeq: 6,
    domainCode: 'NQ',
    domainSeq: 10
  }, {
    topicCode: 'FCC.7',
    topicDesc: null,
    topicName: null,
    topicSeq: 7,
    domainCode: 'NQ',
    domainSeq: 10
  }, {
    topicCode: 'RCN.8',
    topicDesc: null,
    topicName: null,
    topicSeq: 8,
    domainCode: 'NQ',
    domainSeq: 10
  }, {
    topicCode: 'RMV.9',
    topicDesc: null,
    topicName: null,
    topicSeq: 9,
    domainCode: 'NQ',
    domainSeq: 10
  }, {
    topicCode: 'MVB.10',
    topicDesc: null,
    topicName: null,
    topicSeq: 10,
    domainCode: 'NQ',
    domainSeq: 10
  }, {
    topicCode: 'SPU.11',
    topicDesc: null,
    topicName: null,
    topicSeq: 11,
    domainCode: 'NQ',
    domainSeq: 10
  }]
}, {
  domainCode: 'A',
  domainName: null,
  domainSeq: 11,
  topics: [{
    topicCode: 'ISE.1',
    topicDesc: null,
    topicName: null,
    topicSeq: 1,
    domainCode: 'A',
    domainSeq: 11
  }, {
    topicCode: 'IZF.2',
    topicDesc: null,
    topicName: null,
    topicSeq: 2,
    domainCode: 'A',
    domainSeq: 11
  }, {
    topicCode: 'IMM.3',
    topicDesc: null,
    topicName: null,
    topicSeq: 3,
    domainCode: 'A',
    domainSeq: 11
  }, {
    topicCode: 'TEE.4',
    topicDesc: null,
    topicName: null,
    topicSeq: 4,
    domainCode: 'A',
    domainSeq: 11
  }, {
    topicCode: 'PAO.5',
    topicDesc: null,
    topicName: null,
    topicSeq: 5,
    domainCode: 'A',
    domainSeq: 11
  }, {
    topicCode: 'COE.6',
    topicDesc: null,
    topicName: null,
    topicSeq: 6,
    domainCode: 'A',
    domainSeq: 11
  }, {
    topicCode: 'CTE.7',
    topicDesc: null,
    topicName: null,
    topicSeq: 7,
    domainCode: 'A',
    domainSeq: 11
  }, {
    topicCode: 'RCE.8',
    topicDesc: null,
    topicName: null,
    topicSeq: 8,
    domainCode: 'A',
    domainSeq: 11
  }, {
    topicCode: 'RFU.9',
    topicDesc: null,
    topicName: null,
    topicSeq: 9,
    domainCode: 'A',
    domainSeq: 11
  }, {
    topicCode: 'USE.10',
    topicDesc: null,
    topicName: null,
    topicSeq: 10,
    domainCode: 'A',
    domainSeq: 11
  }, {
    topicCode: 'SLEI.11',
    topicDesc: null,
    topicName: null,
    topicSeq: 11,
    domainCode: 'A',
    domainSeq: 11
  }, {
    topicCode: 'SQE.12',
    topicDesc: null,
    topicName: null,
    topicSeq: 12,
    domainCode: 'A',
    domainSeq: 11
  }, {
    topicCode: 'SSE.13',
    topicDesc: null,
    topicName: null,
    topicSeq: 13,
    domainCode: 'A',
    domainSeq: 11
  }, {
    topicCode: 'RSE.14',
    topicDesc: null,
    topicName: null,
    topicSeq: 14,
    domainCode: 'A',
    domainSeq: 11
  }, {
    topicCode: 'FGS.15',
    topicDesc: null,
    topicName: null,
    topicSeq: 15,
    domainCode: 'A',
    domainSeq: 11
  }, {
    topicCode: 'URB.16',
    topicDesc: null,
    topicName: null,
    topicSeq: 16,
    domainCode: 'A',
    domainSeq: 11
  }, {
    topicCode: 'UPI.17',
    topicDesc: null,
    topicName: null,
    topicSeq: 17,
    domainCode: 'A',
    domainSeq: 11
  }, {
    topicCode: 'ABT.18',
    topicDesc: null,
    topicName: null,
    topicSeq: 18,
    domainCode: 'A',
    domainSeq: 11
  }, {
    topicCode: 'RRE.19',
    topicDesc: null,
    topicName: null,
    topicSeq: 19,
    domainCode: 'A',
    domainSeq: 11
  }, {
    topicCode: 'RSE.20',
    topicDesc: null,
    topicName: null,
    topicSeq: 20,
    domainCode: 'A',
    domainSeq: 11
  }]
}, {
  domainCode: 'F',
  domainName: null,
  domainSeq: 12,
  topics: [{
    topicCode: 'DEC.1',
    topicDesc: null,
    topicName: null,
    topicSeq: 1,
    domainCode: 'F',
    domainSeq: 12
  }, {
    topicCode: 'UFM.2',
    topicDesc: null,
    topicName: null,
    topicSeq: 2,
    domainCode: 'F',
    domainSeq: 12
  }, {
    topicCode: 'UCF.3',
    topicDesc: null,
    topicName: null,
    topicSeq: 3,
    domainCode: 'F',
    domainSeq: 12
  }, {
    topicCode: 'IFT.4',
    topicDesc: null,
    topicName: null,
    topicSeq: 4,
    domainCode: 'F',
    domainSeq: 12
  }, {
    topicCode: 'GLQ.5',
    topicDesc: null,
    topicName: null,
    topicSeq: 5,
    domainCode: 'F',
    domainSeq: 12
  }, {
    topicCode: 'GSC.6',
    topicDesc: null,
    topicName: null,
    topicSeq: 6,
    domainCode: 'F',
    domainSeq: 12
  }, {
    topicCode: 'GPF.7',
    topicDesc: null,
    topicName: null,
    topicSeq: 7,
    domainCode: 'F',
    domainSeq: 12
  }, {
    topicCode: 'GRF.8',
    topicDesc: null,
    topicName: null,
    topicSeq: 8,
    domainCode: 'F',
    domainSeq: 12
  }, {
    topicCode: 'GEL.9',
    topicDesc: null,
    topicName: null,
    topicSeq: 9,
    domainCode: 'F',
    domainSeq: 12
  }, {
    topicCode: 'AFB.10',
    topicDesc: null,
    topicName: null,
    topicSeq: 10,
    domainCode: 'F',
    domainSeq: 12
  }, {
    topicCode: 'IEE.11',
    topicDesc: null,
    topicName: null,
    topicSeq: 11,
    domainCode: 'F',
    domainSeq: 12
  }, {
    topicCode: 'CFD.12',
    topicDesc: null,
    topicName: null,
    topicSeq: 12,
    domainCode: 'F',
    domainSeq: 12
  }, {
    topicCode: 'BFT.13',
    topicDesc: null,
    topicName: null,
    topicSeq: 13,
    domainCode: 'F',
    domainSeq: 12
  }, {
    topicCode: 'CAG.14',
    topicDesc: null,
    topicName: null,
    topicSeq: 14,
    domainCode: 'F',
    domainSeq: 12
  }, {
    topicCode: 'BNF.15',
    topicDesc: null,
    topicName: null,
    topicSeq: 15,
    domainCode: 'F',
    domainSeq: 12
  }, {
    topicCode: 'IWI.16',
    topicDesc: null,
    topicName: null,
    topicSeq: 16,
    domainCode: 'F',
    domainSeq: 12
  }, {
    topicCode: 'CCL.17',
    topicDesc: null,
    topicName: null,
    topicSeq: 17,
    domainCode: 'F',
    domainSeq: 12
  }, {
    topicCode: 'IEF.18',
    topicDesc: null,
    topicName: null,
    topicSeq: 18,
    domainCode: 'F',
    domainSeq: 12
  }, {
    topicCode: 'EEM.19',
    topicDesc: null,
    topicName: null,
    topicSeq: 19,
    domainCode: 'F',
    domainSeq: 12
  }, {
    topicCode: 'EDT.20',
    topicDesc: null,
    topicName: null,
    topicSeq: 20,
    domainCode: 'F',
    domainSeq: 12
  }, {
    topicCode: 'MPP.21',
    topicDesc: null,
    topicName: null,
    topicSeq: 21,
    domainCode: 'F',
    domainSeq: 12
  }, {
    topicCode: 'PAT.22',
    topicDesc: null,
    topicName: null,
    topicSeq: 22,
    domainCode: 'F',
    domainSeq: 12
  }, {
    topicCode: 'DRB.23',
    topicDesc: null,
    topicName: null,
    topicSeq: 23,
    domainCode: 'F',
    domainSeq: 12
  }, {
    topicCode: 'RUC.24',
    topicDesc: null,
    topicName: null,
    topicSeq: 24,
    domainCode: 'F',
    domainSeq: 12
  }, {
    topicCode: 'CIT.25',
    topicDesc: null,
    topicName: null,
    topicSeq: 25,
    domainCode: 'F',
    domainSeq: 12
  }]
}];
